sudo: required

language: python

python:
  - 2.7

services:
  - docker

before_install:
  - sudo apt-get install -y python-dev libpq-dev
  - docker build -t pgclient/system_test pgclient/system_test
  - sudo service docker restart ; sleep 10
  - docker run -d -p "0.0.0.0:15432:5432" -e POSTGRES_PORT=15432 -e POSTGRES_PASSWORD=test -e PSQL_ENTRYPOINT=/docker-entrypoint-initdb.d pgclient/system_test
  - sleep 5
  - docker ps -a

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - make system_test

after_success:
  coveralls