sudo: required

language: python

python:
  - 2.7

services:
  - docker

before_install:
  - docker build -t pgclient/system_test pgclient/system_test
  - sudo service docker restart ; sleep 10
  - docker run -d -p "0.0.0.0:5432:5432" -e "POSTGRES_PASSWORD=test" -e "PSQL_ENTRYPOINT=/docker-entrypoint-initdb.d" pgclient/system_test
  - sleep 10
  - docker ps -a

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - make system_test

after_success:
  coveralls